- name: Configure App
  hosts: app
  become: true
  vars:
   db_host: 192.168.10.7
  tasks:
    - copy: src=files/puma.service dest=/etc/systemd/system/puma.service
      notify: reload puma
    - name: Add config for DB connection
      template:
        src: templates/db_config.j2
        dest: /home/ubuntu/db_config
        owner: ubuntu
        group: ubuntu
    - systemd: name=puma enabled=yes
  handlers:
    - systemd: name=puma state=restarted
